apiVersion: v2
name: langflow-ide
description: Helm chart for Langflow IDE
type: application
version: 0.0.1
appVersion: 1.0-alpha

dependencies:
  - name: postgresql
    version: 15.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
