apiVersion: v2
name: langflow-ide
description: Helm chart for Langflow IDE
type: application
version: 0.1.1
appVersion: latest
maintainers:
  - name: Langflow
    email: contact@langflow.org
dependencies:
  - name: postgresql
    version: 15.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
